### ISSUE TITLE
A cool application is incomplete without offline feature

### ISSUE THREAD

**Issue by reeversedev** [reeversedev/devdevdev#14]
Need to implement Service Worker in this application. 

Not really sure about what features can be there in offline mode but for now installing it as an application on the phone looks cool too.

**Comment by rajrajhans** [comment]
Hi, if this is still pending, I'd love to pick it up.

**Comment by reeversedev** [comment]
@rajrajhans Sure! Assigning it to you.

**Comment by reeversedev** [comment]
Hey @rajrajhans! 

Thanks a lot for contributing to this project. This feature actually makes the project even more accessible and in my opinion with some more work, we can actually make this a fully-fledged offline app too. 

Merging this. 🚀

**Comment by rajrajhans** [comment]
Definitely! We can implement aggressive caching policies to make it a fully fledged offline app. 

Although, we must be careful to not cache resources that might change later since if those resources exist in the cache, there will not be GET request made, and the user won't be able to see the latest changes.
